### ISSUE TITLE
Indigo incorrectly calculates RNA coordinates with data from FASTA/Sequence file

### ISSUE THREAD

**Issue by baranovdv** [epam/Indigo#1910]
**Steps to Reproduce**
1. Enter Ketcher Macromolecules mode
2. Open following FASTA file as RNA: [Load FASTA or Sequence file that contains few monomers causes their overlaping on the canvas.zip](https://github.com/epam/ketcher/files/14780775/Load.FASTA.or.Sequence.file.that.contains.few.monomers.causes.their.overlaping.on.the.canvas.zip)

**Actual behavior**
System put on the canvas sequence elements that overlaps each other
![image](https://github.com/epam/ketcher/assets/26869421/9fbf40f1-24e8-4e48-9981-ebe91ddf6087)

**Expected behavior**
All nucleosides are distributed on the canvas without overlaping
![image](https://github.com/epam/ketcher/assets/26869421/8118ef51-fc4d-48cb-8343-af456fe777ae)

Related
- https://github.com/epam/Indigo/issues/1755
- https://github.com/epam/ketcher/issues/4280
- https://github.com/epam/ketcher/issues/4355

**Environment details:**
[Ketcher](https://lifescience.opensource.epam.com/ketcher/index.html)
Version 2.20.0-rc.2
[Indigo Toolkit](http://lifescience.opensource.epam.com/indigo/)
Version 1.19.0-rc.3.0

Win10
Chrome Version 123.0.6312.106 (Official Build) (64-bit)

**Additional context**
Such request with 2 RNA molecules to the Indigo API:

```
data:  
  format: "ket" 
  options:  
    aromatize-skip-superatoms: true 
    dearomatize-on-load: false 
    gross-formula-add-rsites: true 
    ignore-no-chiral-flag: false 
    ignore-stereochemistry-errors: true 
    input-format: "chemical/x-rna-fasta" 
    mass-skip-error-on-pseudoatoms: false 
    smart-layout: true 
  struct: ">SEQUENCE1\nA\n>SEQUENCE2\nA" 
type: 1 
```

gives us response with 4 monomers, where coordinates of monomer1 and monomer2 are the same, that causes overlapping:

```
"monomer0": { 
    "type": "monomer", "id": "0", "seqid": 1, "position": { 
      "x": 0.0, 
      "y": -0.0 
    }, "alias": "R", "templateId": "Rib" 
  }, "monomer1": { 
    "type": "monomer", "id": "1", "seqid": 1, "position": { 
      "x": 0.0, 
      "y": -1.600000023841858 
    }, "alias": "A", "templateId": "Ade" 
  }, "monomer2": { 
    "type": "monomer", "id": "2", "seqid": 1, "position": { 
      "x": 0.0, 
      "y": -1.600000023841858 
    }, "alias": "R", "templateId": "Rib" 
  }, "monomer3": { 
    "type": "monomer", "id": "3", "seqid": 1, "position": { 
      "x": 0.0, 
      "y": -3.200000047683716 
    }, "alias": "A", "templateId": "Ade" 
  } 
```
